#!/system/bin/sh

BASE_DIR="$(cd "$(dirname "$0")" && pwd)"

if [ -z "$1" ]; then
    echo "Usage: ./xsc file.sh"
    exit 1
fi

TARGET="$1"

if [ ! -f "$TARGET" ]; then
    echo "File tidak ditemukan!"
    exit 1
fi

# Detect python
if command -v python3 >/dev/null 2>&1; then
    PYTHON=python3
elif command -v python >/dev/null 2>&1; then
    PYTHON=python
else
    echo "Python tidak ditemukan!"
    exit 1
fi

$PYTHON "$BASE_DIR/XSHIELD.py" "$TARGET"